name: Build Plugin

on:
  push:
    branches: [ master, 2021.1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build plugin
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        arguments: buildPlugin --stacktrace -PintellijPublishToken=none
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SpecFlowPlugin
        path: output/